-- CREATE TABLE students (
--     student_id INT PRIMARY KEY AUTO_INCREMENT,
--     first_name VARCHAR(50) NOT NULL,
--     last_name VARCHAR(50) NOT NULL,
--     date_of_birth DATE NOT NULL,
--     gender ENUM('Male', 'Female') NOT NULL,
--     house ENUM('Gryffindor', 'Hufflepuff', 'Ravenclaw', 'Slytherin') NOT NULL,
--     pet_name VARCHAR(50),
--     quidditch_team BOOLEAN DEFAULT FALSE
-- );

-- CREATE TABLE courses (
--     course_id INT AUTO_INCREMENT PRIMARY KEY,
--     course_name VARCHAR(100) NOT NULL,
--     professor VARCHAR(100) NOT NULL
-- );

-- CREATE TABLE enrollments (
--     enrollment_id INT AUTO_INCREMENT PRIMARY KEY,
--     student_id INT NOT NULL,
--     course_id INT NOT NULL,
--     FOREIGN KEY (student_id) REFERENCES students(student_id),
--     FOREIGN KEY (course_id) REFERENCES courses(course_id)
-- );
